[CONTENT REVIEW] 6.6 - Atualização do Readme do projeto JS Unit test
betrybe/sd-0x-project-js-unit-tests pull request #11
Opened 2020-12-07 12:11 UTC by isabellavjs

[Closes 2467](https://github.com/betrybe/course/issues/2467)

2020-12-07 16:03 UTC, roziscoding requested changes

2020-12-07 16:03 UTC, roziscoding commented on README.md
> +  - Serão um dia de projeto;
```suggestion
  - Será um dia de projeto;
```

2020-12-07 16:03 UTC, roziscoding commented on README.md
> +**⚠️ É importante que seus arquivos tenham exatamente estes nomes! ⚠️**. Você pode adicionar outros arquivos se julgar necessário. Qualquer dúvida, procure a Pessoa Instrutora que te acompanha.
Achei um pouco contraditório dizermos aqui que a pessoa pode criar novos arquivos quando dissemos, ali em cima, que os arquivos já estão todos criados.
Talvez caiba algo como "apesar de não ser necessário para aprovação no projeto, você pode criar novos arquivos, caso ache necessário"

2020-12-08 11:24 UTC, isabellavjs commented on README.md
> +**⚠️ É importante que seus arquivos tenham exatamente estes nomes! ⚠️**. Você pode adicionar outros arquivos se julgar necessário. Qualquer dúvida, procure a Pessoa Instrutora que te acompanha.
Concordo que ficou um pouco ambiguo mesmo, obrigada @roziscoding ! Já corrigi.

2020-12-09 14:32 UTC, cleytonoliveira commented on README.md
> +## Instruções para entregar seu projeto:
Estamos sem um playbook e isso complica, mas seguindo o modelo dos meninos Essa parte seria após data de entrega. Você achou que não fez sentido?

2020-12-09 14:33 UTC, cleytonoliveira approved these changes

2020-12-09 16:11 UTC, roziscoding approved these changes

2020-12-10 11:33 UTC, merged