new getCharacter requirement
betrybe/sd-0x-project-js-unit-tests pull request #28
Opened 2021-05-18 19:33 UTC by isaacbatst

2021-05-19 01:51 UTC, antoniosb requested changes
o arquivo package-lock.json deveria estar aqui?

não tá faltando alterar o README?

2021-05-21 16:16 UTC, isaacbatst commented
> o arquivo package-lock.json deveria estar aqui?
> 
> não tá faltando alterar o README?

Fala @antoniosb! Obrigado por comentar do package-lock, alterou automaticamente aqui pq eu to usando o npm 7, vou desfazer a alteração nele.

Sim! Está faltando o README!

2021-05-24 13:41 UTC, antoniosb approved these changes

2021-05-24 14:02 UTC, gfpoliva approved these changes
O novo requisito foi cadastrado no forest?

2021-06-21 22:26 UTC, merged