[REQUISITO OBJCALCULATOR]
betrybe/sd-0x-project-js-unit-tests pull request #41
Opened 2021-08-25 13:07 UTC by alexandremhm

Alterações:

* Modifica os testes de assert para jest;
* Inclui a função arrayGenerator para contemplar assunto de métodos de objetos no projeto;
* Modifica o nome do requisito para objPlayground;
* ALtera o Readme para contemplar as alterações no requisito.

2021-08-30 18:31 UTC, cleytonoliveira requested changes
Achei que ficou bem melhor. Parabéns @alexandremhm

2021-08-30 18:31 UTC, cleytonoliveira commented on README.md
> +  - Um número inteiro;
```suggestion
  - Dois números inteiros.
```

2021-08-30 18:31 UTC, cleytonoliveira commented on README.md
> +  calculator(1,2) // { sum: 3, mult: 2, div: 1, sub: 0 }
```suggestion
  calculator(1, 2); // { sum: 3, mult: 2, div: 1, sub: 0 }
```

2021-08-30 18:31 UTC, cleytonoliveira commented on README.md
> +  Depois de ter implementado a função calculator, implemente uma função que converta objetos em arrays, de chaves, valores ou ambos.
```suggestion
  Depois de ter implementado a função calculator, desenvolva uma função que converta objetos em arrays, de chaves, valores ou ambos.
```

2021-08-30 18:31 UTC, cleytonoliveira commented on src/objPlayground.js
> +  calculator(1,2) // { sum: 3, mult: 2, div: 1, sub: 0 }
```suggestion
  calculator(1, 2); // { sum: 3, mult: 2, div: 1, sub: 0 }
```

2021-08-30 18:31 UTC, cleytonoliveira commented on src/objPlayground.js
> +  - Dois números inteiros.
Era para esta assim lá em cima?

2021-08-30 18:31 UTC, cleytonoliveira commented on tests/objPlayground.spec.js
> +  calculator(1,2) // { sum: 3, mult: 2, div: 1, sub: 0 }
```suggestion
  calculator(1, 2); // { sum: 3, mult: 2, div: 1, sub: 0 }
```

2021-08-30 18:31 UTC, cleytonoliveira commented on tests/objPlayground.spec.js
> +describe('7 - Implemente a função `objCalculator`', () => {
```suggestion
describe('7 - Implemente a função `calculator`', () => {
```

2021-08-30 18:31 UTC, cleytonoliveira commented on tests/objPlayground.spec.js
> +  it('Verifica se a função `objCalculator` retorna os valores esperados', () => {
```suggestion
  it('Verifica se a função `calculator` retorna os valores esperados', () => {
```

2021-08-31 12:07 UTC, Luiz-Wendel approved these changes

2021-08-31 12:28 UTC, cleytonoliveira commented on tests/objPlayground.spec.js
> +  it('Verifica se a função `arrayGenerator` retorna os valores esperados', () => {
```suggestion

  it('Verifica se a função `arrayGenerator` retorna os valores esperados', () => {
```

2021-08-31 12:28 UTC, cleytonoliveira approved these changes

2021-08-31 12:52 UTC, merged