Revisão geral do readme após finalização para fazer os ajustes necessários; #5162
betrybe/sd-0x-project-js-unit-tests pull request #54
Opened 2021-09-03 13:45 UTC by marcoglnd

2021-09-08 11:25 UTC, Luiz-Wendel commented on README.md
Por algum motivo não consigo selecionar os requisitos 7 e 8, então vou por aqui.

No requisito 7 ficou faltando especificar qual arquivo deve ser utilizado, acho importante ter pois o nome do arquivo não está ligado a nenhuma das funções. (arquivo objPlayground.js).

Já no requisito 8, conforme comentado com o @cleytonoliveira, acho válido comentar que a pessoa estudante deve corrigir as linhas de código disponíveis na função, e não deletar nenhum dos for's presente nela.

2021-09-08 13:32 UTC, Luiz-Wendel approved these changes
Show Marco!

2021-09-08 13:46 UTC, cleytonoliveira requested changes

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
Queria sua opinião, mas não acha que esta muito generalista o que vai ser avaliado? Será que faz sentido colocarmos o que será avaliado de fato ou estaria ajudando a não olharem para os testes?

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
Semelhante ao anterior, será que deveríamos pontuar os casos de testes que devem ser feitos aqui?
Ex:
Deverá testar se a função retorna `true` ao passar um array somente com números por parâmetro;
....
...

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +A função myCounter possui dois loops aninhados que inserem valores dentro de um array. Como podemos perceber, eles vão adicionando valores ao array até sua condição de parada. Corrija a função `myCou
Vale a pena alterar no arquivo myCounter.js e myCounter.spec.js também

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +Você é responsável por elaborar o sistema de pedidos de um restaurante. Deve ser possível, através desse sistema, cadastrar um menu. Dado que um menu foi cadastrado, o sistema deve disponibilizar um
Acredito que de pra sincronizar com o arquivo restaurant.js e restaurant.spec.js aqui

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +1. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se a função `createMenu()` retorna um objeto que possui a chave `fetchMenu`, a qual tem como valor uma função.
idem anterior

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +7. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se, ao chamar uma função associada à chave `order` no objeto retornado, passando uma string como parâmetro (como `objetoRetorna
```suggestion
7. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se ao chamar uma função associada à chave `order` no objeto retornado, passando uma string como parâmetro (como `objetoRetornado.order('coxinha')`), tal string é adicionada ao array retornado em `objetoRetornado.consumption`.
```

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +9. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se, ao adicionar três pedidos, dentre bebidas e comidas, o array `objetoRetornado.consumption` contém os itens pedidos.
```suggestion
9. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se ao adicionar três pedidos, dentre bebidas e comidas, o array `objetoRetornado.consumption` contém os itens pedidos.
```

2021-09-08 13:46 UTC, cleytonoliveira commented on README.md
> +2. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se `'objetoRetornado.fetchMenu()'` retorna um objeto cujas chaves são somente `food` e `drink`, considerando que a função `crea
idem anterior

2021-09-08 13:51 UTC, marcoglnd commented on README.md
> +A função myCounter possui dois loops aninhados que inserem valores dentro de um array. Como podemos perceber, eles vão adicionando valores ao array até sua condição de parada. Corrija a função `myCou
O Luiz fez essa alteração [nesse PR](https://github.com/betrybe/sd-0x-project-js-unit-tests/pull/55)

2021-09-08 13:54 UTC, marcoglnd commented on README.md
> +1. No arquivo `tests/restaurant.spec.js`, escreva um teste que verifica se a função `createMenu()` retorna um objeto que possui a chave `fetchMenu`, a qual tem como valor uma função.
Já foi feito 🤔

2021-09-09 18:35 UTC, joicyoliv commented on README.md
>    ```
Seria interessante acrescentar a parte:  _Implemente as funções `calculator` e `arrayGenerator` de maneira que elas atendam aos testes propostos._ :)

2021-09-09 18:35 UTC, joicyoliv commented on README.md
Acho interessante colocar uma quantidade mínima de teste como sugeri no requisito 2. :)

2021-09-09 19:58 UTC, cleytonoliveira approved these changes

2021-09-09 20:00 UTC, cleytonoliveira commented on README.md
> +A função `numbers` recebe um array (tamanho variável) e retorna `true` se todos os parâmetros forem do tipo 'number' e `false` caso contrário. Essa função já está implementada no arquivo `src/numbers
@joicyoliv acredito que faça sentido, mas será que resolve de fato o problema?

2021-09-09 21:38 UTC, joicyoliv commented on README.md
> +A função `numbers` recebe um array (tamanho variável) e retorna `true` se todos os parâmetros forem do tipo 'number' e `false` caso contrário. Essa função já está implementada no arquivo `src/numbers
@cleytonoliveira seria apenas um paliativo enquanto não tem o teste dos testes. :)

2021-09-10 12:49 UTC, marcoglnd commented on README.md
> +A função `numbers` recebe um array (tamanho variável) e retorna `true` se todos os parâmetros forem do tipo 'number' e `false` caso contrário. Essa função já está implementada no arquivo `src/numbers
@joicyoliv valeu pelas sugestões, fiz as alterações propostas 🚀😁

2021-09-13 12:21 UTC, merged